config/routes.rb
Rails.application.routes.draw do
  # Static artwork pages
  get 'artwork/copic'
  get 'artwork/paintings'
  get 'artwork/sketches'
  get 'artwork/for_sale'

  # Static photo pages
  get 'photos/nature'
  get 'photos/wildlife'
  get 'photos/locations'

  # Admin page for Dad
  get 'welcome/admin'

  resources :artwork, :photos, :profile, :contact, :commissions

  root 'welcome#index'
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  has_attached_file :s3,
  :storage => :s3,
  :bucket => "petermcburneyartwork",
  :s3_region => ENV['AWS_REGION'],
  :s3_host_name => 's3-us-west-2.amazonaws.com',
  :s3_credentials => {
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
    :s3_endpoint => "s3-us-west-2"
  },
  :url =>':s3_domain_url'

  validates :title, presence: true
  validates_attachment_content_type :s3, :content_type => /\Aimage\/.*\Z/
end

app/controllers/artwork_controller.rb
###
# Artwork controller
# Coded by: Andrew McBurney
###

class ArtworkController < ApplicationController
  # basic authentication for all pages except index, copic, sketches, paintings, and for_sale (public facing views)
  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD'], except: [:index, :copic, :sketches, :paintings, :for_sale]

  # ***************************
  # Create Methods
  # ***************************

  # Instantiate a new artwork with default parameters
  def new
    @artwork = Artwork.new(:artwork_type => "painting", :featured => "false", :for_sale => "false")
  end

  # Create artwork and save to database, redirect to admin panel
  def create
    @artwork = Artwork.new(artwork_params)

    if @artwork.save
      redirect_to :controller => 'welcome', :action => 'admin'
    else
      redirect_to :controller => 'artwork', :action => 'new'
    end
  end

  # ***************************
  # Read Methods
  # ***************************

  # Aggregate by featured artwork (featured boolean)
  def index
     @artwork = Artwork.where(:featured => true).order(:order)
  end

  # Aggregate by copic marker paintings
  def copic
    @copic = Artwork.where(:artwork_type => 'copic').order(:order)
  end

  # Aggregate by sketches
  def sketches
    @sketches = Artwork.where(:artwork_type => 'sketch').order(:order)
  end

  # Aggregate by paintings
  def paintings
    @paintings = Artwork.where(:artwork_type => 'painting').order(:order)
  end

  # Select artwork where for_sale is true
  def for_sale
    @for_sale = Artwork.where(:for_sale => true).order(:order)
  end

  #***************************
  # Update Methods
  #***************************

  # Find artwork to be updated
  def edit
    @artwork = Artwork.find(params[:id])
  end

  # Update artwork with new params, redirect to admin panel
  def update
    @artwork = Artwork.find(params[:id])

    if @artwork.update(artwork_params)
      redirect_to :controller => 'welcome', :action => 'admin'
    else
      render 'edit'
    end
  end

  # ***************************
  # Delete Methods
  # ***************************

  # Find artwork by id and delete from database, redirect to admin panel
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy

    redirect_to :controller => 'welcome', :action => 'admin'
  end

  # ***************************
  # Private Methods
  # ***************************

  private
    def artwork_params
      params.require(:artwork).permit(:title, :s3, :image_url, :featured, :order, :artwork_type, :media, :size, :for_sale, :price)
    end
end

app/helpers/artwork_helper.rb
module ArtworkHelper
  # TODO:
  # add ruby helper code and
  # abstract away the logic from the
  # slim files (views)
end

app/views/artwork/copic.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Copic Markers'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | Here are a few selected pieces using 'copic markers'.
        hr[style="margin-bottom:25px;"]
      .artwork-wrapper.pos-rel
        = render :partial => "shared/images", object: @copic, as: 'images'
      hr
      = link_to "Artwork", controller: "artwork", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"

app/views/artwork/edit.slim
main#edit.general
  = render :partial => "shared/nav", locals: {title: 'Edit Artwork'}
  .container
    .inner
      h1
        | Parameters
      hr
      = form_for :artwork, url: artwork_path(@artwork), method: :patch do |f|
        div[style="overflow:hidden;"]
          section.float-left
            h4
              = f.label :title
            = f.text_field :title
          section.float-left
            h4
              = f.label :image_url
            = f.text_field :image_url
          section.float-left
            h4
              = f.label :artwork_type
            p.float-left
              | Painting
              br
              = f.radio_button :artwork_type, "painting"
            p.float-left
              | Copic
              br
              = f.radio_button :artwork_type, "copic"
            p.float-left
              | Sketch
              br
              = f.radio_button :artwork_type, "sketch"
          section.float-left
            h4
              = f.label :media
            = f.text_field :media
          section.float-left
            h4
              = f.label :size
            = f.text_field :size
          section.float-left
            h4
              = f.label :for_sale
            p.float-left
              | True
              br
              = f.radio_button :for_sale, "true"
            p.float-left
              | False
              br
              = f.radio_button :for_sale, "false"
          section.float-left
            h4
              = f.label :price
            = f.text_field :price
          section.float-left
            h4
              = f.label :featured
            p.float-left
              | True
              br
              = f.radio_button :featured, "true"
            p.float-left
              | False
              br
              = f.radio_button :featured, "false"
          section.float-left
            h4
              = f.label :order
            = f.text_field :order, :class => 'order'
          .float-left
            = f.submit
            br
            = link_to 'Destroy', artwork_path(@artwork), method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }
      h1
        | Preview
      hr
      figure.center-horizontal
        |  <img src="
        = @artwork.image_url
        | ">
        figcaption
          h2.title
            = @artwork.title
          hr
          p
            span.media
              = @artwork.media
            | ,
            span.size
              = @artwork.size
            b[style="float:right;"]
              span.price
                = @artwork.price
  = render :partial => "shared/footer"

app/views/artwork/for_sale.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Artwork For Sale'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | The following pieces of art are currently for sale. If you're interested in buying, please reach out to me
          = link_to "here", controller: "contact", action: "index"
          | .
        hr[style="margin-bottom:25px;"]
      .artwork-wrapper.pos-rel
        = render :partial => "shared/images", object: @for_sale, as: 'images'
      hr
      = link_to "Back", controller: "artwork", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"

app/views/artwork/index.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Featured Artwork'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | Here are a few select artwork pieces from my collection. Sketches, copic marker paintings, acrylic paintings, oil paintings, and artwork for sale may be found from the links below.
        = link_to "For Sale", controller: "artwork", action: "for_sale"
        = link_to "Copic Markers", controller: "artwork", action: "copic"
        = link_to "Paintings", controller: "artwork", action: "paintings"
        = link_to "Sketches", controller: "artwork", action: "sketches"
        hr[style="margin-bottom:25px;"]
      .artwork-wrapper.pos-rel
        = render :partial => "shared/images", object: @artwork, as: 'images'
      hr
      = link_to "Home", controller: "welcome", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"

app/views/artwork/new.slim
main#new.general
  = render :partial => "shared/nav", locals: {title: 'Add new artwork'}
  .container
    .inner
      h1
        | Parameters
      hr
      div[style="overflow:hidden;"]
        = form_for :artwork, url: artwork_index_path, html: { multipart: true } do |f|
          div[style="overflow:hidden;"]
            section.float-left
              h4
                = f.label :title
              = f.text_field :title
            section.float-left
              h4
                = f.label :image_url
              = f.text_field :image_url
            section.float-left
              h4
                = f.label :artwork_type
              p.float-left
                | Painting
                br
                = f.radio_button :artwork_type, "painting"
              p.float-left
                | Copic
                br
                = f.radio_button :artwork_type, "copic"
              p.float-left
                | Sketch
                br
                = f.radio_button :artwork_type, "sketch"
            section.float-left
              h4
                = f.label :media
              = f.text_field :media
            section.float-left
              h4
                = f.label :size
              = f.text_field :size
            section.float-left
              h4
                = f.label :for_sale
              p.float-left
                | True
                br
                = f.radio_button :for_sale, "true"
              p.float-left
                | False
                br
                = f.radio_button :for_sale, "false"
            section.float-left
              h4
                = f.label :price
              = f.text_field :price
            section.float-left
              h4
                = f.label :featured
              p.float-left
                | True
                br
                = f.radio_button :featured, "true"
              p.float-left
                | False
                br
                = f.radio_button :featured, "false"
            section.float-left
              h4
                = f.label :order
              = f.text_field :order, :class => 'order'
            .float-left
              = f.submit
      hr
      h1
        | Preview
      hr
      figure.center-horizontal
        img[src="https://s3.amazonaws.com/petermcburneyartwork/paintings/breaching_orca.jpg"]
        figcaption
          h2.title
          hr
          p
            span.media
            | ,
            span.size
            b[style="float:right;"]
              span.price
  = render :partial => "shared/footer"

app/views/artwork/paintings.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Paintings'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | The images below are some of the paintings I have done throughout my career as an artist.
        hr[style="margin-bottom:25px;"]
      .artwork-wrapper.pos-rel
        = render :partial => "shared/images", object: @paintings, as: 'images'
      hr
      = link_to "Artwork", controller: "artwork", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"

app/views/artwork/sketches.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Sketches'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | Here are a few sketches I've done throughout the years.
        hr[style="margin-bottom:25px;"]
      .artwork-wrapper.pos-rel
        = render :partial => "shared/images", object: @sketches, as: 'images'
      hr
      = link_to "Artwork", controller: "artwork", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"