config/routes.rb
Rails.application.routes.draw do
  # Static artwork pages
  get 'artwork/copic'
  get 'artwork/paintings'
  get 'artwork/sketches'
  get 'artwork/for_sale'

  # Static photo pages
  get 'photos/nature'
  get 'photos/wildlife'
  get 'photos/locations'

  # Admin page for Dad
  get 'welcome/admin'

  resources :artwork, :photos, :profile, :contact, :commissions

  root 'welcome#index'
end

app/views/shared/_artwork.slim
.artwork-wrapper.pos-rel
  - images.each_with_index do |image, index|
    .float-left
      = link_to edit_artwork_path(image) do
        .image.margin-left-large id="img#{index}" style=("background:url(#{image.image_url});background-size:cover;background-position: center center;")
          .art-text
            h3.title.pos-abs.col-white style=("left:5px;margin:5px 0px;opacity:1 !important") = image.title
            hr.pos-abs style="width:100%;top:30px;color:white;" /
            p.media.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")
              - if image.respond_to?(:media)
                = image.media
              - elsif image.respond_to?(:location)
                = image.location
            - if image.respond_to?(:size)
              p.size.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")
                = image.size
            - if image.respond_to?(:for_sale)
              - if image.for_sale
                p.price.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")
                  | $ #{image.price}
              - else
                p.price.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")  SOLD

app/views/shared/_footer.slim
span.borderTop
footer
  .pos-rel.inner.shad-retro
    h4 Copyright © Peter McBurney 2017

app/views/shared/_images.slim
- images.each_with_index do |image, index|
  .float-left
    .image.margin-left-large id="img#{index}" style=("background:url(#{image.image_url});background-size:cover;background-position: center center;")
      .art-text
        h3.title.pos-abs= image.title
        hr.pos-abs/
        p.media.pos-rel
          - if image.respond_to?(:media)
            = image.media
          - elsif image.respond_to?(:location)
            = image.location
        - if image.respond_to?(:size)
          p.size.pos-rel
            = image.size
        - if image.respond_to?(:for_sale)
          - if image.for_sale
            p.price.pos-rel
              | $ #{image.price}
          - else
            p.price.pos-rel SOLD

app/views/shared/_nav.slim
nav.pos-rel.col-white.gradient-to-black
  h1.shad-retro= title
span.borderBottom

app/views/shared/_photos.slim
.photo-wrapper.pos-rel
  - images.each_with_index do |image, index|
    .float-left
      = link_to edit_photo_path(image) do
        .image.margin-left-large id="img#{index}" style=("background:url(#{image.image_url});background-size:cover;background-position: center center;")
          .art-text
            h3.title.pos-abs.col-white style=("left:5px;margin:5px 0px;opacity:1 !important") = image.title
            hr.pos-abs style="width:100%;top:30px;color:white;" /
            p.media.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")
              - if image.respond_to?(:media)
                = image.media
              - elsif image.respond_to?(:location)
                = image.location
            - if image.respond_to?(:size)
              p.size.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")
                = image.size
            - if image.respond_to?(:for_sale)
              - if image.for_sale
                p.price.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")
                  | $ #{image.price}
              - else
                p.price.pos-rel.col-white style=("top:25px;left:5px;opacity:1 !important")  SOLD

app/views/shared/_preview.slim
/! IMAGE PREVIEWER
summary#previewer
  figure
    img#image/
    img#x src="../../assets/general/x.png" /
    img#arrow-left src="../../assets/general/arrow-left.png" /
    img#arrow-right src="../../assets/general/arrow-right.png" /
    figcaption
      h2.title
      hr/
      p
        span.media
        span.size
        b style="float:right;"
          span.price