config/routes.rb
Rails.application.routes.draw do
  # Static artwork pages
  get 'artwork/copic'
  get 'artwork/paintings'
  get 'artwork/sketches'
  get 'artwork/for_sale'

  # Static photo pages
  get 'photos/nature'
  get 'photos/wildlife'
  get 'photos/locations'

  # Admin page for Dad
  get 'welcome/admin'

  resources :artwork, :photos, :profile, :contact, :commissions

  root 'welcome#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :s3,
  :storage => :s3,
  :bucket => "petermcburneyartwork",
  :s3_region => ENV['AWS_REGION'],
  :s3_host_name => 's3-us-west-2.amazonaws.com',
  :s3_credentials => {
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
    :s3_endpoint => "s3-us-west-2"
  },
  :url =>':s3_domain_url'

  validates :title, presence: true
  validates_attachment_content_type :s3, :content_type => /\Aimage\/.*\Z/
end

app/controllers/photos_controller.rb
###
# Photos controller
# Coded by: Andrew McBurney
###

class PhotosController < ApplicationController
  # basic authentication for all pages except index, show, nature, wildlife and locations (public facing views)
  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD'], except: [:index, :show, :nature, :wildlife, :locations]

  # ***************************
  # Create Methods
  # ***************************

  # Instantiate new photo with default parameters
  def new
    @photo = Photo.new(:image_type => "nature", :featured => "false")
  end

  # Create photo and save to database, redirect to admin panel
  def create
    @photo = Photo.new(photo_params)

    @photo.save
    redirect_to :controller => 'welcome', :action => 'admin'
  end

  # ***************************
  # Read Methods
  # ***************************


  # Aggregate by featured photos (featured boolean)
  def index
    @photos = Photo.where(:featured => true).order(:order)
  end

  # Aggregate by nature photos
  def nature
    @nature = Photo.where(:image_type => "nature").order(:order)
  end

  # Aggregate by wildlife photos
  def wildlife
    @wildlife = Photo.where(:image_type => "wildlife").order(:order)
  end

  # Aggregate by location photos
  def locations
    @locations = Photo.where(:image_type => "locations").order(:order)
  end

  #***************************
  # Update Methods
  #***************************

  # Find photo to be updated
  def edit
    @photo = Photo.find(params[:id])
  end

  # Updated photo with new params, redirect to admin panel
  def update
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
      redirect_to :controller => 'welcome', :action => 'admin'
    else
      render 'edit'
    end
  end

  # ***************************
  # Delete Methods
  # ***************************

  # Find a photo by id and delete from database, redirect to admin panel
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to :controller => 'welcome', :action => 'admin'
  end

  # ***************************
  # Private Methods
  # ***************************

  private
    def photo_params
      params.require(:photo).permit(:title, :image_type, :image_url, :location, :featured, :order)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
  # TODO:
  # add ruby helper code and
  # abstract away the logic from the
  # slim files (views)
end

app/views/photos/edit.slim
main#edit.general
  = render :partial => "shared/nav", locals: {title: 'Edit Photo'}
  .container
    .inner
      h1
        | Parameters
      hr
      = form_for :photo, url: photo_path(@photo), method: :patch do |f|
        div[style="overflow:hidden;"]
          section.float-left
            h4
              = f.label :title
            = f.text_field :title
          section.float-left
            h4
              = f.label :image_url
            = f.text_field :image_url
          section.float-left
            h4
              = f.label :image_type
            p.float-left
              | Nature
              br
              = f.radio_button :image_type, "nature"
            p.float-left
              | Wildlife
              br
              = f.radio_button :image_type, "wildlife"
            p.float-left
              | Locations
              br
              = f.radio_button :image_type, "locations"
          section.float-left
            h4
              = f.label :location
            = f.text_field :location
          section.float-left
            h4
              = f.label :featured
            p.float-left
              | True
              br
              = f.radio_button :featured, "true"
            p.float-left
              | False
              br
              = f.radio_button :featured, "false"
          section.float-left
            h4
              = f.label :order
            = f.text_field :order, :class => 'order'
          .float-left
            = f.submit
            br
            = link_to 'Destroy', photo_path(@photo), method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }
      h1
        | Preview
      hr
      figure.center-horizontal
        |  <img src="
        = @photo.image_url
        | ">
        figcaption
          h2.title
            = @photo.title
          hr
          p
            span.media
              = @photo.location
  = render :partial => "shared/footer"

app/views/photos/index.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Featured Photography'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | Here are a few featured photographs from my collection. Nature, wildlife, and landmark photography may be found from the links below.
        = link_to "Nature", controller: "photos", action: "nature"
        = link_to "Wildlife", controller: "photos", action: "wildlife"
        = link_to "Locations", controller: "photos", action: "locations"
        hr[style="margin-bottom:25px;"]
      .photo-wrapper.pos-rel
        = render :partial => "shared/images", object: @photos, as: 'images'
      hr
      = link_to "Home", controller: "welcome", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"

app/views/photos/locations.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Locations'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | Here are a few images of locations and landmarks taken throughout the years.
        hr[style="margin-bottom:25px;"]
      .photo-wrapper.pos-rel
        = render :partial => "shared/images", object: @locations, as: 'images'
      hr
      = link_to "Photos", controller: "photos", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"

app/views/photos/nature.slim
.general
  = render 'shared/preview'
  = render :partial => "shared/nav", locals: {title: 'Nature Shots'}
  .container
    .inner
      .text-wrapper
        p[style="font-size:20px;"]
          | Here are a few nature images that showcase the beautiful landscape of the world.
        hr[style="margin-bottom:25px;"]
      .photo-wrapper.pos-rel
        = render :partial => "shared/images", object: @nature, as: 'images'
      hr
      = link_to "Photos", controller: "photos", action: "index"
      img.pos-rel[src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right"]
  = render :partial => "shared/footer"

app/views/photos/new.slim
main#new.general
  /! Nav
  = render :partial => "shared/nav", locals: {title: 'Add new photo'}
  .container
    .inner
      h1 Parameters
      hr/
      div style="overflow:hidden;"
        = form_for :photo, url: photos_path, html: { multipart: true } do |f|
          div style="overflow:hidden;"
            /! Title
            section.float-left
              h4= f.label :title
              = f.text_field :title
            /! URL
            section.float-left
              h4= f.label :image_url
              = f.text_field :image_url
            /! Image Type
            section.float-left
              h4= f.label :image_type
              p.float-left
                | Nature
                br/
                = f.radio_button :image_type, "nature"
              p.float-left
                | Wildlife
                br/
                = f.radio_button :image_type, "wildlife"
              p.float-left
                | Locations
                br/
                = f.radio_button :image_type, "locations"
            /! Location
            section.float-left
              h4= f.label :location
              = f.text_field :location
            /! Featured
            section.float-left
              h4= f.label :featured
              p.float-left
                | True
                br/
                = f.radio_button :featured, "true"
              p.float-left
                | False
                br/
                = f.radio_button :featured, "false"
            /! Order
            section.float-left
              h4= f.label :order
              = f.text_field :order, :class => 'order'
            /! Submit
            .float-left
              = f.submit
      /! New Image Previewer
      /! TODO: make this a partial
      h1 Preview
      hr/
      figure.center-horizontal
        img src="https://s3.amazonaws.com/petermcburneyartwork/paintings/breaching_orca.jpg" /
        figcaption
          h2.title
          hr/
          p
            span.media
            | ,
            span.size
            b style="float:right;"
              span.price

app/views/photos/wildlife.slim
.general
  /! Image previewer
  = render 'shared/preview'
  /! Nav
  = render :partial => "shared/nav", locals: {title: 'Wildlife Photos'}
  /! Art grid system
  .container
    .inner
      .text-wrapper
        p style="font-size:20px;"  These images showcase the some of the wildlife I have photographed in recent years.
        hr style="margin-bottom:25px;" /
      .photo-wrapper.pos-rel
        = render :partial => "shared/images", object: @wildlife, as: 'images'
      hr/
      = link_to "Photos", controller: "photos", action: "index"
      img.pos-rel src="https://s3.amazonaws.com/petermcburneyartwork/general/signature_black.png" style="width:300px;height:auto;float:right" /
  /! Footer
  = render :partial => "shared/footer"